## Simple SVM

In [1]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC, LinearSVC, NuSVC
from sklearn.metrics import accuracy_score
import pandas as pd

C:\Users\Lab\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [2]:
from ucimlrepo import fetch_ucirepo 
car_evaluation = fetch_ucirepo(id=19) 

X = car_evaluation.data.features 
y = car_evaluation.data.targets 

In [28]:
car_evaluation.variables

name     role         type demographic  \
0    buying  Feature  Categorical        None   
1     maint  Feature  Categorical        None   
2     doors  Feature  Categorical        None   
3   persons  Feature  Categorical        None   
4  lug_boot  Feature  Categorical        None   
5    safety  Feature  Categorical        None   
6     class   Target  Categorical        None   

                                         description units missing_values  
0                                       buying price  None             no  
1                           price of the maintenance  None             no  
2                                    number of doors  None             no  
3              capacity in terms of persons to carry  None             no  
4                           the size of luggage boot  None             no  
5                        estimated safety of the car  None             no  
6  evaulation level (unacceptable, acceptable, go...  None             no

In [29]:
car_evaluation.variables['description'][6]

'evaulation level (unacceptable, acceptable, good, very good)'

In [3]:
df = pd.concat([X,y], axis=1)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   class     1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
encoder = LabelEncoder()

In [7]:
for i in X.columns:
    if X[i].dtype=='object':
        X.loc[:,i] = encoder.fit_transform(X[i])
    print(X[i].value_counts())

buying
3    432
0    432
2    432
1    432
Name: count, dtype: int64
maint
3    432
0    432
2    432
1    432
Name: count, dtype: int64
doors
0    432
1    432
2    432
3    432
Name: count, dtype: int64
persons
0    576
1    576
2    576
Name: count, dtype: int64
lug_boot
2    576
1    576
0    576
Name: count, dtype: int64
safety
1    576
2    576
0    576
Name: count, dtype: int64


In [8]:
X = pd.get_dummies(X, columns=X.columns, drop_first=True)

In [9]:
X

buying_1  buying_2  buying_3  maint_1  maint_2  maint_3  doors_1  \
0        False     False      True    False    False     True    False   
1        False     False      True    False    False     True    False   
2        False     False      True    False    False     True    False   
3        False     False      True    False    False     True    False   
4        False     False      True    False    False     True    False   
...        ...       ...       ...      ...      ...      ...      ...   
1723      True     False     False     True    False    False    False   
1724      True     False     False     True    False    False    False   
1725      True     False     False     True    False    False    False   
1726      True     False     False     True    False    False    False   
1727      True     False     False     True    False    False    False   

      doors_2  doors_3  persons_1  persons_2  lug_boot_1  lug_boot_2  \
0       False    False      False      False       False        True   
1       False    False      False      False       False        True   
2       False    False      False      False       False        True   
3       False    False      False      False        True       False   
4       False    False      False      False        True       False   
...       ...      ...        ...        ...         ...         ...   
1723    False     True      False       True        True       False   
1724    False     True      False       True        True       False   
1725    False     True      False       True       False       False   
1726    False     True      False       True       False       False   
1727    False     True      False       True       False       False   

      safety_1  safety_2  
0         True     False  
1        False      True  
2        False     False  
3         True     False  
4        False      True  
...        ...       ...  
1723     False      True  
1724     False     False  
1725      True     False  
1726     False      True  
1727     False     False  

[1728 rows x 15 columns]

In [10]:
X = X.astype(int)
X

buying_1  buying_2  buying_3  maint_1  maint_2  maint_3  doors_1  \
0            0         0         1        0        0        1        0   
1            0         0         1        0        0        1        0   
2            0         0         1        0        0        1        0   
3            0         0         1        0        0        1        0   
4            0         0         1        0        0        1        0   
...        ...       ...       ...      ...      ...      ...      ...   
1723         1         0         0        1        0        0        0   
1724         1         0         0        1        0        0        0   
1725         1         0         0        1        0        0        0   
1726         1         0         0        1        0        0        0   
1727         1         0         0        1        0        0        0   

      doors_2  doors_3  persons_1  persons_2  lug_boot_1  lug_boot_2  \
0           0        0          0          0           0           1   
1           0        0          0          0           0           1   
2           0        0          0          0           0           1   
3           0        0          0          0           1           0   
4           0        0          0          0           1           0   
...       ...      ...        ...        ...         ...         ...   
1723        0        1          0          1           1           0   
1724        0        1          0          1           1           0   
1725        0        1          0          1           0           0   
1726        0        1          0          1           0           0   
1727        0        1          0          1           0           0   

      safety_1  safety_2  
0            1         0  
1            0         1  
2            0         0  
3            1         0  
4            0         1  
...        ...       ...  
1723         0         1  
1724         0         0  
1725         1         0  
1726         0         1  
1727         0         0  

[1728 rows x 15 columns]

In [11]:
y=df.iloc[:,-1]

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [13]:
svm = SVC()
svm.fit(X_train, y_train)
y_pred_svm = svm.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_svm)
print("Accuracy:", accuracy)

Accuracy: 0.9421965317919075


In [14]:
lin_svm = SVC(kernel='linear')
lin_svm.fit(X_train, y_train)
y_pred_lin = lin_svm.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_lin)
print("Accuracy:", accuracy)

Accuracy: 0.9190751445086706


In [15]:
rbf_svm = SVC(kernel='rbf')
rbf_svm.fit(X_train, y_train)
y_pred_rbf = rbf_svm.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_rbf)
print("Accuracy:", accuracy)

Accuracy: 0.9421965317919075


In [16]:
soft_svm = SVC(kernel='linear', C=5, gamma='scale')
soft_svm.fit(X_train, y_train)
y_pred_soft = soft_svm.predict(X_test)
y_pred_soft_train = soft_svm.predict(X_train)
accuracy_on_test = accuracy_score(y_test, y_pred_soft)
accuracy_on_train = accuracy_score(y_train, y_pred_soft_train)
print("Accuracy on Test data:", accuracy_on_test)
print("Accuracy on Train data:", accuracy_on_train)

Accuracy on Test data: 0.9267822736030829
Accuracy on Train data: 0.9503722084367245


In [17]:
poly_svm = SVC(kernel='poly', degree=3)
poly_svm.fit(X_train, y_train)
y_pred_poly = poly_svm.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_poly)
print("Accuracy:", accuracy)

Accuracy: 0.953757225433526


In [18]:
nu_svm = NuSVC(nu=0.09, kernel='rbf')
nu_svm.fit(X_train, y_train)
y_pred_nu = nu_svm.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_nu)
print("Accuracy:", accuracy)

Accuracy: 0.9710982658959537


In [19]:
models = [svm, lin_svm, rbf_svm, soft_svm, poly_svm, nu_svm]

In [20]:
for i in models:
    print(i.n_support_)


[244  50 282  41]
[177  43 134  35]
[244  50 282  41]
[146  43 111  33]
[176  44 224  39]
[209  48 224  41]


In [21]:
for i in models:
    print("indices of sv for " , i)
    print(i.support_)


indices of sv for  SVC()
[   2   10   12   15   17   29   32   34   35   42   57   62   66   69
   71   79   80   82   94   98   99  101  132  133  139  145  146  156
  157  161  167  169  172  176  179  181  185  187  204  209  218  228
  232  250  264  268  275  281  283  286  287  295  298  301  305  316
  326  333  338  341  350  351  353  354  360  367  383  384  387  393
  399  406  412  416  422  430  441  460  462  475  476  479  482  487
  490  492  493  496  498  500  504  505  506  510  513  518  524  530
  535  541  542  545  548  555  561  563  567  577  583  586  588  601
  603  604  607  618  625  628  630  632  634  638  645  659  674  682
  689  695  696  699  700  701  703  705  707  716  717  720  727  729
  741  752  757  761  763  765  769  772  778  788  796  800  804  808
  809  818  822  823  828  831  832  836  846  848  861  865  866  873
  876  884  890  892  893  894  895  897  910  918  925  931  936  942
  948  949  951  953  955  962  964  969  974  975  

In [22]:
for i in models:
    print(i.support_vectors_)

[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 0.]
 [1. 0. 0. ... 0. 0. 1.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]
[[1. 0. 0. ... 0. 0. 1.]
 [1. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]]


In [37]:
X

buying_1  buying_2  buying_3  maint_1  maint_2  maint_3  doors_1  \
1178         0         1         0        0        1        0        0   
585          0         0         0        0        0        0        1   
1552         1         0         0        0        1        0        1   
1169         0         1         0        0        1        0        0   
1033         0         1         0        0        0        0        0   
...        ...       ...       ...      ...      ...      ...      ...   
1130         0         1         0        0        1        0        1   
1294         0         1         0        1        0        0        0   
860          0         0         0        1        0        0        0   
1459         1         0         0        0        0        0        0   
1126         0         1         0        0        1        0        1   

      doors_2  doors_3  persons_1  persons_2  lug_boot_1  lug_boot_2  \
1178        0        1          1          0           0           0   
585         0        0          0          1           0           1   
1552        0        0          1          0           1           0   
1169        0        1          0          0           0           0   
1033        1        0          0          0           0           0   
...       ...      ...        ...        ...         ...         ...   
1130        0        0          0          1           1           0   
1294        0        1          0          1           0           0   
860         0        1          0          1           1           0   
1459        1        0          0          0           0           1   
1126        0        0          0          1           0           1   

      safety_1  safety_2  
1178         0         0  
585          1         0  
1552         0         1  
1169         0         0  
1033         0         1  
...        ...       ...  
1130         0         0  
1294         0         1  
860          0         0  
1459         0         1  
1126         0         1  

[1209 rows x 15 columns]

In [38]:
import numpy as np
import matplotlib.pyplot as plt
X = df.iloc[:,:-1]
y = df.iloc[:,-1]
h = .02  
# create a mesh to plot in
x_min, x_max = X[:, 0].min() - 1, X[:, 0].max() + 1
y_min, y_max = X[:, 1].min() - 1, X[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, h),
                     np.arange(y_min, y_max, h))
# title for the plots
titles = ['SVC with linear kernel',
          'LinearSVC (linear kernel)',
          'SVC with RBF kernel',
          'SVC with polynomial (degree 3) kernel']
for i, clf in enumerate(tuple(models)):
    # Plot the decision boundary. For that, we will assign a color to each
    # point in the mesh [x_min, x_max]x[y_min, y_max].
    plt.subplot(2, 2, i + 1)
    plt.subplots_adjust(wspace=0.4, hspace=0.4)

    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])

    # Put the result into a color plot
    Z = Z.reshape(xx.shape)
    plt.contourf(xx, yy, Z, cmap=plt.cm.coolwarm, alpha=0.8)

    # Plot also the training points
    plt.scatter(X[:, 0], X[:, 1], c=y, cmap=plt.cm.coolwarm)
    plt.xlabel('Sepal length')
    plt.ylabel('Sepal width')
    plt.xlim(xx.min(), xx.max())
    plt.ylim(yy.min(), yy.max())
    plt.xticks(())
    plt.yticks(())
    plt.title(titles[i])

plt.show()

InvalidIndexError: (slice(None, None, None), 0)